dist: xenial
language: python
python: 3.7
script: python -m compileall ./
cache: pip
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: jack1142
  password:
    secure: "VwDFUvfdCd3/lHI0UKLYTlQdKlRXqYSoIHNkcHxs39aZ1KkH4HgQqSpXX3kBoxu4rKsO0NFOl8rZBlHenoymJeB10Cu8j62rSSGzwDL0lNNXTw6HpqY0GBz7DyxC4UekKQ8Q7wkE3ziRxd5HTiA327xj/YY4AvUTJ9/cFr1kX23fh8KIpkZ/u51SV1hSDbXVV16VcqZn4u6WLVNroymcsRhMu4uxOeHReOJDFn28ySar1bQTNK+EJYk7x9Dt+LYteXTSGO6/cfS4dE/636yPPC9zzZ3reAEBEu8bbGDMrNHKOf4wBOuKI5jPnUuwwO0Qjz8Wqg9YdwonTfXmxn2Bt+MWWNh7KlfveiYQHSxsY3yhCsutREQeTFY3QjrvyvAOdaGM41MhF01MC7NEHyK/BoM4K2JOcc4OxdiiwCYyGB+SDAIdssQ6WAqN5UoDrD2dU39T2pnbjj50m2HQkDXwnEbB6JU9DQzkmc6HfoVGWMtP9EjcdDES25WnSx9qrZwf8yzfkONKx1V1ZerRaZPksChQrk9AK4BLX0irI8Eg8m7L3T1EehZ4mg4qzOKxLjL3r6DQzP/P8KWs1g+ZXZEUxROzlHBXuyHo3IY3cvGULEry4+5VMUaVP7Fv36eq7eWptRhqFfgTWUjQd/7XlWy3CaiyjX4ACg9QxuJdaN2xkX0="
  skip_cleanup: true
  on:
    repo: jack1142/rlapi
    tags: true
