dist: xenial
language: python
python:
  - 3.7
  - 3.8
script:
  - pip install -U .[tests]
  - python -m compileall ./
  - mypy rlapi rlapi/ext
jobs:
  include:
    - name: "Style check"
      python: 3.7
      script:
        - pip install -U .[style]
        - black --check ./
    - name: "Build docs"
      python: 3.7
      script:
        - pip install -U .[docs]
        - sphinx-build docs docs/_build/html -W -b html
        - sphinx-build docs docs/_build/linkcheck -W -b linkcheck
cache: pip
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: jack1142
  password:
    secure: "VwDFUvfdCd3/lHI0UKLYTlQdKlRXqYSoIHNkcHxs39aZ1KkH4HgQqSpXX3kBoxu4rKsO0NFOl8rZBlHenoymJeB10Cu8j62rSSGzwDL0lNNXTw6HpqY0GBz7DyxC4UekKQ8Q7wkE3ziRxd5HTiA327xj/YY4AvUTJ9/cFr1kX23fh8KIpkZ/u51SV1hSDbXVV16VcqZn4u6WLVNroymcsRhMu4uxOeHReOJDFn28ySar1bQTNK+EJYk7x9Dt+LYteXTSGO6/cfS4dE/636yPPC9zzZ3reAEBEu8bbGDMrNHKOf4wBOuKI5jPnUuwwO0Qjz8Wqg9YdwonTfXmxn2Bt+MWWNh7KlfveiYQHSxsY3yhCsutREQeTFY3QjrvyvAOdaGM41MhF01MC7NEHyK/BoM4K2JOcc4OxdiiwCYyGB+SDAIdssQ6WAqN5UoDrD2dU39T2pnbjj50m2HQkDXwnEbB6JU9DQzkmc6HfoVGWMtP9EjcdDES25WnSx9qrZwf8yzfkONKx1V1ZerRaZPksChQrk9AK4BLX0irI8Eg8m7L3T1EehZ4mg4qzOKxLjL3r6DQzP/P8KWs1g+ZXZEUxROzlHBXuyHo3IY3cvGULEry4+5VMUaVP7Fv36eq7eWptRhqFfgTWUjQd/7XlWy3CaiyjX4ACg9QxuJdaN2xkX0="
  skip_cleanup: true
  on:
    repo: jack1142/rlapi
    python: 3.7
    tags: true
