[tool.black]
target-versions = ['py37', 'py38']
exclude = '''
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | stubs/lxml
  )/
'''

[tool.isort]
profile = "black"
combine_as_imports = true
skip = [
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "_build",
    "buck-out",
    "build",
    "dist",
    "stubs/lxml",
]
